#!/usr/bin/env python3
"""Build docs/hub.html — the one-stop landing page ("web poster").

Same visual language as the print poster (black line work on paper),
but the three central links are live buttons. The hero line drawing is
generated by the same code as the print poster, so it can never drift
from the configs. Small QR codes let someone scan the links straight
off another person's screen. Everything is embedded — one file.
"""
import base64
import io
import os
import sys

import qrcode
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)
from configs.v16_configs import CONFIGS, ROOM_W, ROOM_L  # noqa: E402
from project_urls import WALKTHROUGH_URL, DOWNLOAD_URL, DECK_URL  # noqa: E402
from build_poster import draw_plan_grid  # noqa: E402

LINKS = [
    ("Walk it", "walkthrough",
     "A first-person tour of all nine layouts. It auto-walks each room "
     "in from the Main Entrance — or click in and take the controls.",
     WALKTHROUGH_URL),
    ("Get the PDF", "download page",
     "One tap, one file: the twelve-page options study with sightlines "
     "and pros & cons, plus the one-page comparison sheet.",
     DOWNLOAD_URL),
    ("Weigh the options", "decision deck",
     "Set the weights to what the house values — play, hospitality, "
     "service, events — and watch the nine layouts re-rank live.",
     DECK_URL),
]


def png_uri(img):
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def qr_uri(url):
    q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M,
                      box_size=6, border=1)
    q.add_data(url)
    q.make(fit=True)
    return png_uri(q.make_image(fill_color="#17171a",
                                back_color="#f7f6f2").convert("L"))


def main():
    hero = png_uri(draw_plan_grid(CONFIGS, cell_h=470, label_h=44,
                                  gap=30, stroke=3))

    key_a = "  ".join(f"{c['letter']} {c['short']}" for c in CONFIGS[:5])
    key_b = "  ".join(f"{c['letter']} {c['short']}" for c in CONFIGS[5:])

    poster_pdf = os.path.join(ROOT, "docs", "pool_room_poster.pdf")
    with open(poster_pdf, "rb") as fh:
        poster_uri = ("data:application/pdf;base64,"
                      + base64.b64encode(fh.read()).decode())

    cards = ""
    for title, kind, blurb, url in LINKS:
        cards += f"""
<a class="card" href="{url}">
  <span class="card-copy">
    <span class="card-kind">{kind}</span>
    <span class="card-title">{title} →</span>
    <span class="card-blurb">{blurb}</span>
    <span class="card-url">{url}</span>
  </span>
  <img class="card-qr" src="{qr_uri(url)}" alt="QR code for {title}">
</a>"""

    html = f"""<title>The Pool Room — Nine Ways to Rack the Room</title>
<style>
  :root {{
    --paper: #f7f6f2; --ink: #17171a; --muted: #6a6a70; --rule: #c9c7c0;
  }}
  * {{ box-sizing: border-box; }}
  body {{
    background: var(--paper); color: var(--ink);
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
    margin: 0; padding: 28px 14px 48px;
    display: flex; justify-content: center;
  }}
  .frame {{
    max-width: 720px; width: 100%;
    border: 3px solid var(--ink); outline: 1px solid var(--ink);
    outline-offset: 5px; padding: clamp(20px, 5vw, 44px);
    display: flex; flex-direction: column; gap: 30px;
  }}
  header {{ text-align: center; display: flex; flex-direction: column;
            gap: 10px; }}
  h1 {{ font-size: clamp(34px, 8vw, 58px); line-height: 1; margin: 0;
        font-weight: 900; letter-spacing: .02em; text-wrap: balance; }}
  .sub {{ font-size: clamp(15px, 3vw, 19px); font-weight: 700;
          letter-spacing: .14em; margin: 0; }}
  .tag {{ font-family: ui-monospace, "Cascadia Mono", Menlo, monospace;
          font-size: 12px; letter-spacing: .12em; color: var(--muted);
          border-top: 2px solid var(--ink); padding-top: 12px; margin: 0;
          text-transform: uppercase; }}
  .hero {{ display: block; margin: 0 auto; width: min(480px, 92%); }}
  .hero img {{ width: 100%; display: block; }}
  .hero figcaption {{
    font-family: ui-monospace, Menlo, monospace; font-size: 11px;
    letter-spacing: .08em; color: var(--muted); text-align: center;
    margin-top: 10px; text-transform: uppercase; }}
  .cards {{ display: flex; flex-direction: column; gap: 16px; }}
  .card {{
    display: flex; gap: 18px; align-items: center;
    background: var(--ink); color: var(--paper);
    text-decoration: none; padding: 18px 20px;
  }}
  .card:hover .card-title, .card:focus-visible .card-title
    {{ text-decoration: underline; text-underline-offset: 4px; }}
  .card:focus-visible {{ outline: 3px solid var(--ink);
                         outline-offset: 3px; }}
  .card-copy {{ display: flex; flex-direction: column; gap: 6px;
                min-width: 0; }}
  .card-kind {{ font-family: ui-monospace, Menlo, monospace;
                font-size: 11px; letter-spacing: .18em;
                text-transform: uppercase; opacity: .75; }}
  .card-title {{ font-size: clamp(20px, 4.5vw, 26px); font-weight: 900; }}
  .card-blurb {{ font-size: 14px; line-height: 1.45; opacity: .85;
                 max-width: 46ch; }}
  .card-url {{ font-family: ui-monospace, Menlo, monospace; font-size: 11px;
               opacity: .6; overflow-wrap: break-word; }}
  .card-qr {{ width: 96px; height: 96px; flex: none; margin-left: auto;
              image-rendering: pixelated; }}
  @media (max-width: 540px) {{ .card-qr {{ display: none; }} }}
  .print {{ text-align: center; font-size: 14px; }}
  .print a {{ color: var(--ink); font-weight: 700; }}
  footer {{ border-top: 2px solid var(--ink); padding-top: 14px;
            display: flex; flex-direction: column; gap: 6px;
            text-align: center; }}
  .key {{ font-family: ui-monospace, Menlo, monospace; font-size: 11.5px;
          letter-spacing: .04em; color: var(--muted); margin: 0;
          text-transform: uppercase; }}
  .oath {{ font-size: 12px; font-weight: 700; letter-spacing: .08em;
           margin: 6px 0 0; }}
</style>
<div class="frame">
  <header>
    <h1>THE POOL ROOM</h1>
    <p class="sub">NINE WAYS TO RACK THE ROOM</p>
    <p class="tag">Six tables · one room · see every option, then decide</p>
  </header>
  <figure class="hero">
    <img src="{hero}" alt="Line drawing floor plans of all nine layouts,
      lettered A through I">
    <figcaption>All nine layouts, A to I — walk any of them below</figcaption>
  </figure>
  <nav class="cards">{cards}
  </nav>
  <p class="print">Putting it on a wall?
    <a href="{poster_uri}" download="pool_room_poster.pdf">Download the
    8.5×14 print poster</a> — same three links as QR codes.</p>
  <footer>
    <p class="key">{key_a}</p>
    <p class="key">{key_b}</p>
    <p class="oath">EVERY NUMBER COMPUTED FROM THE ROOM GEOMETRY —
      NOT ESTIMATED</p>
  </footer>
</div>
"""
    # v47: the hub is the GitHub Pages site root
    out = os.path.join(ROOT, "docs", "index.html")
    with open(out, "w") as fh:
        fh.write(html)
    print(f"wrote {out} ({os.path.getsize(out)/1e6:.2f} MB)")


if __name__ == "__main__":
    main()
